version: '3'
services:
  preprocessor:
    container_name: preprocessor
    build:
      context: ./preprocess
      dockerfile: Dockerfile
    environment: 
      - SUBJECT=PY21N026
      - ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=16
    volumes:
      - /usr/local/freesurfer/7-dev/subjects:/data
      - ./preprocess/scripts:/home/preprocess/scripts:cached
    tty: true
    
  mesh_generator:
    container_name: mesh_generator
    build:
      context: ./generate
      dockerfile: Dockerfile
    environment: 
      - SUBJECT=PY21N026
    volumes:
      - /usr/local/freesurfer/7-dev/subjects:/data
      # - .:/home:cached
      - ./generate:/home/generate:cached
    tty: true

  mesh_visualizer:
    container_name: mesh_visualizer
    build: 
      context: ./visualize
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment: 
      - PORT=80
    volumes:
      - /usr/local/freesurfer/7-dev/subjects:/data
      - ./visualize:/home/visualize:cached
    tty: true