version: '3'
services:
  mesh_generator:
    container_name: mesh_generator
    build:
      context: .
      dockerfile: ./generate.Dockerfile
    environment: 
      - SUBJECTS_DIR=/data
      - SUBJECT=cvs_avg35_inMNI152
    volumes:
      # - $SUBJECTS_DIR:/data
      - /usr/local/freesurfer/subjects:/data

  visualizer:
    container_name: mesh_visualizer
    build: 
      context: .
      dockerfile: ./visualize.Dockerfile
    ports:
      - "80:80"
    environment: 
      - SUBJECTS_DIR=/data
      - SUBJECT=cvs_avg35_inMNI152
      - PORT=80
    volumes:
      # - $SUBJECTS_DIR:/data
      - /usr/local/freesurfer/subjects:/data