version: '3'
services:
  visualizer:
    container_name: mesh_visualizer
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000"
    volumes:
      - ./Data:/data
    environment: 
      - SUBJECT=PY18N011


