version: '3'
services:
  preprocessor:
    container_name: preprocessor
    build:
      context: ./preprocess
      dockerfile: Dockerfile
    environment: 
      - SUBJECT=PY21N023
      - ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=16
    volumes:
      - $SUBJECTS_DIR:/data
      - ./preprocess/scripts:/home/preprocess/scripts:cached
    tty: true
    
  mesh_generator:
    container_name: mesh_generator
    build:
      context: ./generate
      dockerfile: Dockerfile
    environment: 
      - SUBJECT=PY21N023
    volumes:
      - $SUBJECTS_DIR:/data
      - ./generate:/home/generate:cached
    tty: true

  mesh_visualizer:
    container_name: mesh_visualizer
    build: 
      context: ./visualize
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment: 
      - PORT=80
    volumes:
      - $SUBJECTS_DIR:/data
      - ./visualize:/home/visualize
    tty: true