version: '3'
services:
  mesh_generator:
    container_name: mesh_generator
    build:
      context: .
      dockerfile: ./generate.Dockerfile
    environment: 
      - SUBJECTS_DIR=/data/
      - SUBJECT=fsaverage
    volumes:
      - $SUBJECTS_DIR:/data/

  visualizer:
    container_name: mesh_visualizer
    build: 
      context: .
      dockerfile: ./visualize.Dockerfile
    ports:
      - "80:80"
    environment: 
      - SUBJECTS_DIR=/data/
      - SUBJECT=fsaverage
      - PORT=80
    volumes:
      - $SUBJECTS_DIR:/data