version: '3'
services:
  mesh_generator:
    container_name: mesh_generator
    build:
      context: .
      dockerfile: ./generate.Dockerfile
    working_dir: /home/scripts
    environment: 
      - SUBJECTS_DIR=/data
      - SUBJECT=cvs_avg35_inMNI152
    volumes:
      # - $SUBJECTS_DIR:/data
      - /usr/local/freesurfer/subjects:/data
    command: /bin/bash -c ./runscript.sh

  visualizer:
    container_name: mesh_visualizer
    build: 
      context: .
      dockerfile: ./visualize.Dockerfile
    ports:
      - "80:80"
    environment: 
      - SUBJECTS_DIR=/data
      - SUBJECT=cvs_avg35_inMNI152
      - PORT=80
    volumes:
      # - $SUBJECTS_DIR:/data
      - /usr/local/freesurfer/subjects:/data


  # docker build -f ./generate.Dockerfile . -t vizgen
  
  # docker run --env SUBJECTS_DIR=/data --env SUBJECT=cvs_avg35_inMNI152 -v /usr/local/freesurfer/subjects:/data -w /home/scripts -it vizgen:latest /bin/bash -c ./runscript.sh
