version: '3'
services:
  # mesh_generator:
  #   container_name: mesh_generator
  #   build:
  #     context: .
  #     dockerfile: ./generate.Dockerfile
  #   environment: 
  #     - SUBJECT=PY20N014
  #     - SUBJECTS_DIR=/data/
  #   volumes:
  #     - $SUBJECTS_DIR:/data/

  visualizer:
    container_name: mesh_visualizer
    build: 
      context: .
      dockerfile: ./visualize.Dockerfile
    ports:
      - "80:80"
    environment: 
      - SUBJECTS_DIR=/data/
      - SUBJECT=PY20N014
      - PORT=80
    volumes:
      - $SUBJECTS_DIR:/data