version: '3'
services:
  visualizer:
    container_name: mesh_visualizer
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80"
    volumes:
      - /mnt/shared/Subjects:/data
    environment: 
      - SUBJECTS_DIR=/data/derivatives/freesurfer
      - SUBJECT=fsaverage
      - PORT=80

  mesh_generator:
    container_name: mesh_generator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - SUBJECT=fsaverage
    volumes:
      - $SUBJECTS_DIR:/data

