#!/bin/bash
counter=0001
while [ $counter -le 0035 ]; do
	newCount=$(printf "%04g" $counter)
	labelName=$(cat ./roiNames.json | jq '.["'$newCount'"]')
	labelName="${labelName#\"}"
	labelName="${labelName%\"}"
	./srf2obj $SUBJECT/rois/lh.pial_roi.$newCount.srf >$SUBJECT/obj/lh.$labelName.obj
	./srf2obj $SUBJECT/rois/rh.pial_roi.$newCount.srf >$SUBJECT/obj/rh.$labelName.obj
	((counter++))
done
