version: 2.1

jobs:
  python-lint:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout

      # Also restore pip cache to speed up installations
      - restore_cache: # ensure this step occurs *before* installing dependencies
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: Setup Python environment via Pipenv
          # ... but use latest version of EZTrack
          command: |
            sudo pip install --upgrade pip
            sudo pip install pipenv
            pipenv install --skip-lock --dev

      - run:
          name: Run unit and integration tests
          command: |
            pipenv run make check

  test-npm:
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths: node_modules
      - run:
          name: Eslint
          command: npm lint
      # - run:
      #     name: Jest tests
      #     command: yarn coverage --maxWorkers=2
      # - run:
      #     name: Upload to codecov
      #     command: yarn codecov
      # - run:
      #     name: Smoke tests
      # command: bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders && bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders --json
  test_docker_viz:
    machine:
      # Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build -t neuroseek/recon_visualizer:latest -f visualizer.Dockerfile .
      # - run:
      #     name: Smoke tests
      #     command: |
      #       docker run --rm -it -v $PWD/bids-validator/tests/data/valid_headers:/data bids/validator:latest /data --ignoreNiftiHeaders
      #       docker run --rm -it -v $PWD/bids-validator/tests/data/valid_headers:/data bids/validator:latest /data --ignoreNiftiHeaders --json

  test_docker_mesh:
    machine:
      # Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build -t neuroseek/3d_reconstruction:latest -f generate.Dockerfile .
      # - run:
      #     name: Smoke tests
      #     command: |
      #       docker run --rm -it -v $PWD/bids-validator/tests/data/valid_headers:/data bids/validator:latest /data --ignoreNiftiHeaders
      #       docker run --rm -it -v $PWD/bids-validator/tests/data/valid_headers:/data bids/validator:latest /data --ignoreNiftiHeaders --json

workflows:
  commit:
    jobs:
      - python-lint
      - test-npm
      - test-docker_viz
      - test_docker_mesh
#      - docs-deploy:
#          requires:
#            - docs-build
#          filters:
#            branches:
#              only: master

#  scheduled:
#    jobs:
#      - docs-build
#
#    triggers:
#      - schedule:
#          cron: "0 4 * * *"
#          filters:
#            branches:
#              only:
#                - master
